include::chapter-base.adoc[]
== Technics & best practices

=== KISS, YAGNI & DRY

Some popular principles among developers communities:

* **K**eep **I**t **S**tupid **S**imple : The simpler, the better.
However do something in a simple way can be a difficult exercise.
* **Y**ou **A**in’t **G**onna **N**eed **I**t : Only add code useful at the time of its writing.
Predictions on how a piece of software will evolve are often wrong and code structure that was planned may be an obstacle for real evolutions.
* **D**on’t **R**epeat **Y**ourself : Duplication is frowned upon by developers, and bring several issues :
** It's more work, as the same code needs to be written, tested and maintained several times
** In case of a bug, multiple fixes must be done, and some may be forgotten

This same simplicity can be found in two of the twelve principles of the *Agile Manifesto*:

* Our highest priority is to satisfy the customer through early and continuous delivery of [.underline]#*valuable*# software
* Simplicity [the art of maximizing the amount of work not done] is essential.
