include::chapter-base.adoc[]
== Introduction

[quote, Ralph Johnson]
Architecture is about the important stuff.
Whatever that is.


[quote, Martin Fowler]
_____
It means that the heart of thinking architecturally about software is to decide what is important, (i.e. what is architectural), and then expend energy on keeping those architectural elements in good condition.
For a developer to become an architect, they need to be able to recognize what elements are important, recognizing what elements are likely to result in serious problems should they not be controlled.
_____

A piece of software tries to achieve several objectives depending on the context.
Among these objectives, we encounter:

* Maintainability
* Testability
* Reliability / Resilience
* Scalability
* Security
* Performance
* etc.

Software architecture is the technical means used to meet the objectives set for a particular project while complying with constraints.

As all the objectives cannot be met in one development iteration, software architecture is the ideal compromise in regard to project priorities.

Constraints can be:

* Short term realisation / deadline
* Limited funding
* Security compliance
* Connection to a third party software using specific technology / protocol
* etc.

Priorities must be decided by all stakeholders, and periodically adjusted to follow the project evolution.
It is a partnership.

The development team uses architecture principles to reach projects objectives in the best way.
